version: "3"
services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - 5432
  fwla-center:
    image: ihrigb/fwla-center:${FWLA_CENTER_VERSION}
    container_name: fwla-center
    expose:
      - 8080
    environment:
      - mail.receive.host=${MAIL_RECEIVE_HOST}
      - mail.receive.username=${MAIL_RECEIVE_USERNAME}
      - mail.receive.password=${MAIL_RECEIVE_PASSWORD}
      - mail.receive.whitelistHot=${MAIL_RECEIVE_HOT_WHITELIST}
      - mail.receive.whitelistTraining=${MAIL_RECEIVE_TRAINING_WHITELIST}
      - app.geo.home.coordinate.latitude=${APP_GEO_HOME_LATITUDE}
      - app.geo.home.coordinate.longitude=${APP_GEO_HOME_LONGITUDE}
      - app.geo.ors.apiKey=${APP_GEO_ORS_APIKEY}
      - app.weather.openweathermap.apiKey=${APP_WEATHER_OPENWEATHERMAP_APIKEY}
      - spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
      - spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect
      - spring.datasource.username=${POSTGRES_USERNAME}
      - spring.datasource.password=${POSTGRES_PASSWORD}
      - "spring.datasource.url=jdbc:postgresql://postgres:5432/${POSTGRES_DB}"
    depends_on:
      - postgres
  fwla-center-admin:
    image: ihrigb/fwla-center-admin:${FWLA_CENTER_VERSION}
    container_name: fwla-center-admin
    expose:
      - 5000
    depends_on:
      - fwla-center
  fwla-center-display:
    image: ihrigb/fwla-center-display:${FWLA_CENTER_VERSION}
    container_name: fwla-center-display
    expose:
      - 5000
    depends_on:
      - fwla-center
  fwla-center-map:
    image: ihrigb/fwla-center-map:${FWLA_CENTER_VERSION}
    container_name: fwla-center-map
    expose:
      - 5000
    depends_on:
      - fwla-center
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - fwla-center
      - fwla-center-admin
      - fwla-center-display
      - fwla-center-map
