version: '3'
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
  fwla-center:
    image: ihrigb/fwla-center:dev
    container_name: fwla-center
    expose:
      - 8080
    depends_on:
      - postgres
    environment:
      - mail.receive.host=${MAIL_RECEIVE_HOST}
      - mail.receive.username=${MAIL_RECEIVE_USERNAME}
      - mail.receive.password=${MAIL_RECEIVE_PASSWORD}
      - mail.receive.whitelist=${MAIL_RECEIVE_WHITELIST}
      - mail.receive.blacklist=${MAIL_RECEIVE_BLACKLIST}
      - app.weather.openweathermap.apiKey=${APP_WEATHER_OPENWEATHERMAP_APIKEY}
  fwla-center-admin:
    image: ihrigb/fwla-center-admin:dev
    container_name: fwla-center-admin
    expose:
      - 5000
  fwla-center-display:
    image: ihrigb/fwla-center-display:dev
    container_name: fwla-center-display
    expose:
      - 5000
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - fwla-center
      - fwla-center-admin
      - fwla-center-display
