version: "3"
services:
  postgres:
    image: postgres:alpine
    container_name: fwla-center-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - 5432
  fwla-center:
    image: ihrigb/fwla-center:${FWLA_CENTER_VERSION}
    container_name: fwla-center
    expose:
      - 8080
    environment:
      - APP_MAIL_RECEIVE_HOST=${APP_MAIL_RECEIVE_HOST}
      - APP_MAIL_RECEIVE_USERNAME=${APP_MAIL_RECEIVE_USERNAME}
      - APP_MAIL_RECEIVE_PASSWORD=${APP_MAIL_RECEIVE_PASSWORD}
      - APP_MAIL_RECEIVE_WHITELISTHOT=${APP_MAIL_RECEIVE_HOT_WHITELIST}
      - APP_MAIL_RECEIVE_WHITELISTTRAINING=${APP_MAIL_RECEIVE_TRAINING_WHITELIST}
      - APP_GEO_HOME_COORDINATE_LATITUDE=${APP_GEO_HOME_LATITUDE}
      - APP_GEO_HOME_COORDINATE_LONGITUDE=${APP_GEO_HOME_LONGITUDE}
      - APP_GEO_ORS_APIKEY=${APP_GEO_ORS_APIKEY}
      - APP_WEATHER_OPENWEATHERMAP_APIKEY=${APP_WEATHER_OPENWEATHERMAP_APIKEY}
      - SPRING_JPA_PROPERTIES_HIBERNATE_TEMP_USE_JDBC_METADATA_DEFAULTS = false
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQL9Dialect
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}"
    depends_on:
      - postgres
  fwla-center-admin:
    image: ihrigb/fwla-center-admin:${FWLA_CENTER_VERSION}
    container_name: fwla-center-admin
    expose:
      - 5000
    depends_on:
      - fwla-center
  fwla-center-display:
    image: ihrigb/fwla-center-display:${FWLA_CENTER_VERSION}
    container_name: fwla-center-display
    expose:
      - 5000
    depends_on:
      - fwla-center
  fwla-center-map:
    image: ihrigb/fwla-center-map:${FWLA_CENTER_VERSION}
    container_name: fwla-center-map
    expose:
      - 5000
    depends_on:
      - fwla-center
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/www/data/index.html
    ports:
      - 80:80
    depends_on:
      - fwla-center
      - fwla-center-admin
      - fwla-center-display
      - fwla-center-map
