version: '3'
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: secret123
    expose:
      - 5432
  fwla-center:
    image: ihrigb/fwla-center:dev
    container_name: fwla-center
    expose:
      - 8080
    depends_on:
      - postgres
  fwla-center-admin:
    image: ihrigb/fwla-center-admin:dev
    container_name: fwla-center-admin
    expose:
      - 5000
  fwla-center-display:
    image: ihrigb/fwla-center-display:dev
    container_name: fwla-center-display
    expose:
      - 5000
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - fwla-center
      - fwla-center-admin
      - fwla-center-display
