version: '3'
services:
  #postgres:
  #  image: postgres:alpine
  #  environment:
  #    POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #  expose:
  #    - 5432
  #  depends_on:
  #    - postgres
  elasticsearch:
    build: elk/elasticsearch/
    container_name: elasticsearch
    expose:
      - 8080
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
  logstash:
    build: elk/logstash/
    container_name: logstash
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./elk/logstash/config:/etc/logstash/conf.d
    expose:
      - 9999
    depends_on:
      - elasticsearch
  kibana:
    build: elk/kibana/
    container_name: kibana
    volumes:
      - ./elk/kibana/config/:/opt/kibana/config/
    expose:
      - 5601
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  fwla-center:
    image: ihrigb/fwla-center:${FWLA_CENTER_VERSION}
    container_name: fwla-center
    expose:
      - 8080
    environment:
      - mail.receive.host=${MAIL_RECEIVE_HOST}
      - mail.receive.username=${MAIL_RECEIVE_USERNAME}
      - mail.receive.password=${MAIL_RECEIVE_PASSWORD}
      - mail.receive.whitelist=${MAIL_RECEIVE_WHITELIST}
      - mail.receive.blacklist=${MAIL_RECEIVE_BLACKLIST}
      - app.weather.openweathermap.apiKey=${APP_WEATHER_OPENWEATHERMAP_APIKEY}
    depends_on:
      - logstash
  fwla-center-admin:
    image: ihrigb/fwla-center-admin:${FWLA_CENTER_VERSION}
    container_name: fwla-center-admin
    expose:
      - 5000
  fwla-center-display:
    image: ihrigb/fwla-center-display:${FWLA_CENTER_VERSION}
    container_name: fwla-center-display
    expose:
      - 5000
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - fwla-center
      - fwla-center-admin
      - fwla-center-display
      - kibana
